using UnityEngine.UI;
using WS;

public class MainView : View
{
    public Button Retrieval;
    public Button AncientDocuments;
    public Button Collect;
    public Button Prepare;

    public override void LoadInit()
    {
        ShowModeType = ViewShowModeType.Screen;
        ReferenceCollector rc = UIGameObject.GetComponent<ReferenceCollector>();
        Retrieval = rc.GetComponent<Button>("Retrieval");
        AncientDocuments = rc.GetComponent<Button>("AncientDocuments");
        Collect = rc.GetComponent<Button>("Collect");
        Prepare = rc.GetComponent<Button>("Prepare");
    }
}
