using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using WS;




public class HarvestingProcessController : Controller<HarvestingProcessView, HarvestingProcessModel>
{
    public override void Dispose()
    {
        base.Dispose();
    }

    protected override void BindingViewModel()
    {

        this._Model.Bind(this._View.btnBack, () =>
        {
            Debug.Log("·µ»ØÖ÷Ò³Ãæ");

            FacadeComponent.Instance.CreateController<HarvestingProcessController>().OpenView();

            FacadeComponent.Instance.CloseView(this._View, null);
        });






    }
}

public class HarvestingProcessModel : Model
{
    public override void InitProperty()
    {



    }
}

public class HarvestingProcessView : View
{
    public TMPro.TMP_InputField ifMedcineSeach;
    public ScrollRect svSeach;
    public ScrollRect svMedcineAll;
    public TMPro.TextMeshProUGUI txtMedcineDes;
    public TMPro.TextMeshProUGUI txtMedcineName;
    public TMPro.TextMeshProUGUI txtTitle;
    public Button btnEnterClass;
    public Button btnBack;


    public override void LoadInit()
    {
        ShowModeType = ViewShowModeType.Screen;
        ReferenceCollector rc = UIGameObject.GetComponent<ReferenceCollector>();

        ifMedcineSeach = rc.GetComponent<TMP_InputField>("ifMedcineSeach");
        svSeach = rc.GetComponent<ScrollRect>("svSeach");
        svMedcineAll = rc.GetComponent<ScrollRect>("svMedcineAll");
        txtMedcineName = rc.GetComponent<TextMeshProUGUI>("txtMedcineName");
        txtMedcineDes = rc.GetComponent<TextMeshProUGUI>("txtMedcineDes");
        txtTitle = rc.GetComponent<TextMeshProUGUI>("txtTitle");
        btnEnterClass = rc.GetComponent<Button>("btnEnterClass");
        btnBack = rc.GetComponent<Button>("btnBack");


    }
}
